name: Backend CI

on:
  push:
    paths:
      - "golden-movie-studio-backend/**"
  pull_request:
    paths:
      - "golden-movie-studio-backend/**"

jobs:
  backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Instalar Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Instalar dependÃªncias
        run: |
          cd golden-movie-studio-backend
          npm install

      - name: Build da imagem Docker
        run: |
          cd golden-movie-studio-backend
          docker build -t gms-backend .
