name: Backend CI

on:
  push:
    paths:
      - "golden-movie-studio-backend/**"
  pull_request:
    paths:
      - "golden-movie-studio-backend/**"

jobs:
  backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Instalar Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: 'golden-movie-studio-backend/package-lock.json'

      - name: Instalar dependências
        working-directory: ./golden-movie-studio-backend
        run: npm install --ci

      - name: Verificar sintaxe e dependências
        working-directory: ./golden-movie-studio-backend
        run: npm list

      - name: Build da imagem Docker
        working-directory: ./golden-movie-studio-backend
        run: docker build -t gms-backend:latest .
